name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23ligYAdH3wZZ3kifN"
GITHUB_OWNER = "yigebenbi"
GITHUB_REPO = "benbiyige"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = https://benbiyige.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://benbiyige.pages.dev/"

